plugins {
    id 'java'
    id 'war'
    id 'org.springframework.boot' version '3.4.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.hohoedu'
version = '0.0.1-SNAPSHOT'
apply plugin: 'war'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}


configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven { url "https://github.com/linkhub-sdk/Linkhub-maven/raw/master/releases" }
}

dependencies {
    // ✅ Spring Boot 기본 구성
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'junit:junit:4.13.1'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'

    // ✅ Lombok (컴파일용 + 어노테이션 생성용)
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // ✅ MyBatis, JWT, Firebase, Popbill
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.4'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    implementation 'com.google.firebase:firebase-admin:9.2.0'
    implementation 'commons-codec:commons-codec:1.16.0'
    implementation 'kr.co.linkhub:popbill-spring-boot-starter:1.17.0'
    implementation 'commons-net:commons-net:3.9.0'
    implementation 'org.apache.poi:poi-ooxml:5.2.3'

    // ✅ 런타임
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'com.microsoft.sqlserver:mssql-jdbc'

    // ✅ Dev & Servlet
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.1.0'
    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'

}

bootRun {
    jvmArgs = ['-Djava.net.preferIPv4Stack=true']
}

tasks.named('test') {
    useJUnitPlatform()
}
